[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
lib_deps =
  links2004/WebSockets @ ^2.6.1
  adafruit/Adafruit VL53L0X @ ^1.2.4
